# Generated by Django 2.1.4 on 2022-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='date_added',
        ),
    ]
